FROM ubuntu:21.04
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y bpfcc-tools linux-headers-$(uname -r) python3-pip && \
    mkdir /opt/packet_maze/
COPY ./requirements.txt /opt/packet_maze/
COPY ./docker_entrypoint.sh /opt/packet_maze/
RUN python3 -m pip install -r /opt/packet_maze/requirements.txt && chmod +x /opt/packet_maze/docker_entrypoint.sh
WORKDIR /opt/packet_maze/
CMD ["./docker_entrypoint.sh"]
